spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.143/viewpoint?characterEncoding=utf-8&useSSL=false
  jpa:
    #show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH-mm-ss
  #freemarker:
    #template-loader-path: classpath:/templates
    #cache: false
    #charset: utf-8
    #check-template-location: true
    #content-type: text/html
    #expose-request-attributes: true
    #expose-session-attributes: true
    #request-context-attribute: request
    #suffix: .html
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
ftp:
  port: 21
  hostname: 192.168.2.143
  userName: ftpuser
  password: 123456
  basePath: /home/ftpuser
  fileUploadPath: http://192.168.2.143
imooc:
  security:
    browser:
      #loginType:  REDIRECT
      loginPage:  /login.html